Correct URL to download Polaris tar
FairwindsOps/polaris pull request #660
Opened 2021-10-29 18:53 UTC by Jaanki

Closes: https://github.com/FairwindsOps/polaris/issues/659

Signed-Off-By: Janki Chhatbar <jchhatba@redhat.com>

2021-10-29 18:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FairwindsOps/polaris?pullRequest=660) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FairwindsOps/polaris?pullRequest=660) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FairwindsOps/polaris?pullRequest=660) it.</sub>

2021-10-29 18:55 UTC, Jaanki commented
See https://github.com/Jaanki/submariner-operator/pull/3 for a successful action creation after making these changes.

2021-10-29 18:56 UTC, rbren approved these changes

2021-11-01 14:23 UTC, sudermanjr requested changes
It looks to me like we need to update the version in the actions file to the latest version as well.

The reason the `build-ext` job works is that it's pulling the old version in the file (3.0.3) rather than the latest version (which has the new file naming)

So as part of this PR, can you please update these two lines to say 4.2.0:
https://github.com/FairwindsOps/polaris/blob/e31f3f1b4156233cee0abfc38bd7118406c4e181/.github/workflows/test_setup.yml#L14

https://github.com/FairwindsOps/polaris/blob/e31f3f1b4156233cee0abfc38bd7118406c4e181/.github/workflows/test_setup.yml#L25

2021-11-03 07:50 UTC, Jaanki commented on .github/workflows/test_setup.yml
>          uses: fairwindsops/polaris/.github/actions/setup-polaris@master
I think build-ext job will fail until this PR is merged because the job checks out master branch which does not have these changes.

2021-11-03 12:32 UTC, sudermanjr approved these changes

2021-11-03 12:32 UTC, merged